[pytest]
pythonpath = . common conserver api

log_cli = 1
log_cli_level = INFO

markers =
    integration: mark a test that requires external services (redis-stack, etc.). Runs by default; deselect with -m "not integration".
