"""Native-key copy and fail-closed migration checks on disposable Redis."""

from unittest.mock import patch

import pytest
from redis import Redis

from scripts.migrate_redis_json import migrate
from test_plain_redis import plain_redis  # Reuse the private-process fixture.


@pytest.fixture
def endpoints(plain_redis):
    _, socket = plain_redis
    source = Redis(unix_socket_path=socket, db=3)
    target = Redis(unix_socket_path=socket, db=4)
    # These databases belong exclusively to the private test process.
    source.flushdb()
    target.flushdb()
    yield source, target
    source.close()
    target.close()


def test_copy_preserves_native_values_expiry_and_source(endpoints):
    source, target = endpoints
    source.set('owned:config', b'\x00\xff', px=120000)
    source.rpush('owned:queue', 'a', 'a', 'b')
    source.hset('owned:hash', mapping={'field': 'value'})
    source.sadd('owned:set', 'a', 'b')
    source.zadd('owned:index', {'a': 1.5})
    source.xadd('owned:stream', {'event': 'test'})
    source.set('other:untouched', 'private')
    deadline = source.execute_command('PEXPIRETIME', 'owned:config')
    result = migrate(source, target, ['owned:*', 'owned:queue'])
    assert result == {'selected': 6, 'copied': 6, 'expired': 0}
    assert target.get('owned:config') == b'\x00\xff'
    assert target.execute_command('PEXPIRETIME', 'owned:config') == deadline
    assert target.lrange('owned:queue', 0, -1) == [b'a', b'a', b'b']
    assert target.hgetall('owned:hash') == source.hgetall('owned:hash')
    assert target.smembers('owned:set') == source.smembers('owned:set')
    assert target.zrange('owned:index', 0, -1, withscores=True) == [(b'a', 1.5)]
    assert target.xrange('owned:stream') == source.xrange('owned:stream')
    assert target.pttl('owned:queue') == -1
    assert source.dbsize() == 7
    assert target.get('other:untouched') is None


def test_same_database_is_rejected(endpoints):
    source, _ = endpoints
    with pytest.raises(ValueError, match='different databases'):
        migrate(source, source, ['*'])


def test_occupied_target_is_preserved(endpoints):
    source, target = endpoints
    target.set('keep', 'value')
    with pytest.raises(ValueError, match='empty'):
        migrate(source, target, ['*'])
    assert target.get('keep') == b'value'


def test_unknown_module_aborts_before_writing(endpoints):
    source, target = endpoints
    source.set('module-key', 'data')
    with patch.object(source, 'type', return_value=b'unknown-module'):
        with pytest.raises(ValueError, match='Unsupported'):
            migrate(source, target, ['*'])
    assert target.dbsize() == 0


def test_version_downgrade_aborts_before_writing(endpoints):
    source, target = endpoints
    with (
        patch.object(source, 'info', return_value={'run_id': 'source', 'redis_version': '7.4.7'}),
        patch.object(target, 'info', return_value={'run_id': 'target', 'redis_version': '7.2.16'}),
    ):
        with pytest.raises(ValueError, match='target version'):
            migrate(source, target, ['*'])
    assert target.dbsize() == 0


@pytest.mark.integration
def test_redisjson_copy_to_ordinary_redis():
    """CI supplies two disposable services; ordinary unit runs need neither."""
    import json
    import os
    from uuid import uuid4

    source_url = os.getenv('REDISJSON_TEST_SOURCE_URL')
    target_url = os.getenv('REDISJSON_TEST_TARGET_URL')
    if not source_url or not target_url:
        pytest.skip('Requires explicit disposable migration source and target URLs')
    source, target = Redis.from_url(source_url), Redis.from_url(target_url)
    prefix = f'migration:{uuid4()}:'
    keys = [prefix + suffix for suffix in ('json', 'persistent', 'queue')]
    try:
        assert source.dbsize() == target.dbsize() == 0, 'Use empty disposable databases'
        assert not target.module_list(), 'Target must be ordinary Redis'
        value = {'fixture': 'synthetic', 'body': '{"nested": true}', 'items': [None, False, 'café']}
        for key in keys[:2]:
            source.execute_command('JSON.SET', key, '.', json.dumps(value))
        source.pexpire(keys[0], 120000)
        deadline = source.execute_command('PEXPIRETIME', keys[0])
        source.rpush(keys[2], 'a', 'a', 'b')
        assert migrate(source, target, [prefix + '*']) == {'selected': 3, 'copied': 3, 'expired': 0}
        for key in keys[:2]:
            assert json.loads(target.get(key)) == value
            assert source.type(key) == b'ReJSON-RL'
            assert target.type(key) == b'string'
        assert target.execute_command('PEXPIRETIME', keys[0]) == deadline
        assert target.pttl(keys[1]) == -1
        assert target.lrange(keys[2], 0, -1) == source.lrange(keys[2], 0, -1) == [b'a', b'a', b'b']
    finally:
        # Delete only keys generated by this test, never another dataset.
        source.delete(*keys)
        target.delete(*keys)
        source.close()
        target.close()
