name: Python conserver unit test
on: 
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Create Conserver network
      run: |
        docker network create conserver

    - name: Build and run test services
      run: |
        docker-compose -f docker-compose.test.yml up --build --detach

    - name: Wait for services to be ready
      run: |
        echo "Waiting for PostgreSQL to be ready..."
        timeout 60 bash -c 'until docker-compose -f docker-compose.test.yml exec -T postgres pg_isready -U postgres -d vcon_test_db; do 
          echo "PostgreSQL is unavailable - sleeping"
          sleep 2
        done'
        
        echo "Waiting for Redis to be ready..."
        timeout 30 bash -c 'until docker-compose -f docker-compose.test.yml exec -T redis redis-cli ping | grep PONG; do
          echo "Redis is unavailable - sleeping"
          sleep 2
        done'
        
        echo "Services are ready!"

    - name: Run tests
      run: |
        docker-compose -f docker-compose.test.yml run --rm conserver bash -c "
          poetry install &&
          pytest --maxfail=5 --disable-warnings -v
        "

    - name: Show logs on failure
      if: failure()
      run: |
        echo "=== Docker Compose Logs ==="
        docker-compose -f docker-compose.test.yml logs
        echo "=== PostgreSQL Logs ==="
        docker-compose -f docker-compose.test.yml logs postgres
        echo "=== Redis Logs ==="
        docker-compose -f docker-compose.test.yml logs redis

    - name: Clean up
      if: always()
      run: |
        docker-compose -f docker-compose.test.yml down -v
        docker network rm conserver || true